server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: room-service

  datasource:
    url: jdbc:postgresql://localhost:5432/roomsafar_v2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: false
  packages-to-scan: com.roomsafar.room_service
  paths-to-match: /api/**
